### ISSUE TITLE
Dangling promises?

### ISSUE THREAD

**Issue by jcayzac** [privatenumber/manten#3]
Writing asynchronous tests like in this repo's `tests/index.ts`, for instance:

```ts
import { expect, describe } from 'manten'

describe('asynchronous', ({ test }) => {
  test(`should fail`, async () => {
    expect(false).toBe(true)
  })
})
```

…I get eslint errors:

> Promise returned in function argument where a void return was expected. `eslint` [`@typescript-eslint/no-misused-promises`](https://typescript-eslint.io/rules/no-misused-promises)

**Comment by privatenumber** [comment]
You can disable the rule for files that use manten.

The `describe` block collects all `test` calls and awaits on them, so if you want, you can add an `await` on the top level `describe`. If you add an `await` to each `test` call, you'll lose concurrency on tests.
